In [1]:
!pip install -r ../requirements.txt

Requirement already satisfied: clearml in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from -r ../requirements.txt (line 1)) (2.1.8)
Requirement already satisfied: attrs>=18.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (25.4.0)
Requirement already satisfied: furl>=2.0.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (2.1.4)
Requirement already satisfied: jsonschema>=2.6.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (4.26.0)
Requirement already satisfied: pathlib2>=2.3.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (2.3.7.post1)
Requirement already satisfied: psutil>=3.4.2 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (7.0.0)
Requirement already satisfied: pyparsing>=2.0.3 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (3.2.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pyjwt<3.0.0,>=2.4.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (2.13.0)
Requirement already satisfied: PyYAML>=3.12 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (6.0)
Requirement already satisfied: six>=1.16.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: urllib3>=1.21.1 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (2.6.3)
Requirement already satisfied: Pillow>=10.3.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (12.0.0)
Requirement already satisfied: referencing<0.40 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (0.37.0)
Requirement already satisfied: requests>=2.32.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (2.32.5)
Requirement already satisfied: numpy>=1.26.4 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from clearml->-r ../requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: typing_extensions>=4.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from pyjwt<3.0.0,>=2.4.0->clearml->-r ../requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: rpds-py>=0.7.0 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from referencing<0.40->clearml->-r ../requirements.txt (line 1)) (0.28.0)
Requirement already satisfied: orderedmultidict>=1.0.1 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from furl>=2.0.0->clearml->-r ../requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from jsonschema>=2.6.0->clearml->-r ../requirements.txt (line 1)) (2025.9.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from requests>=2.32.0->clearml->-r ../requirements.txt (line 1)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from requests>=2.32.0->clearml->-r ../requirements.txt (line 1)) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/timurmif/ACADEMY/hse/smadimo-hse/.conda/lib/python3.10/site-packages (from requests>=2.32.0->clearml->-r ../requirements.txt (line 1)) (2026.5.20)

In [1]:
import os
import dotenv
dotenv.load_dotenv()

from clearml import Dataset
from utils.datasets import get_dataset
import pandas as pd

In [4]:
tracks = get_dataset('spotify-tracks', 'HSE-GP5')
tracks.head(5)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [3]:
lyrics = get_dataset('spotify-lyrics', 'HSE-GP5')
lyrics.head(5)

,Unnamed: 0,song_id,artist_id,song,artists,explicit,genres,lyrics
0,0,spotify:track:1NbzT9otocflZ9d8yvA54D,spotify:artist:30TrHDLNCKQVTYWOn9QqOC,Better Than Home,['Beth Hart'],False,modern blues,Better than home Lyrics I can feel my body bre...
1,1,spotify:track:1crTf4RvraCjcPoqsaT9hd,spotify:artist:4P0dddbxPil35MNN9G2MEX,Illusions,['Cypress Hill'],True,chicano rap;gangster rap;hardcore hip hop;hip ...,Illusions Lyrics Some people tell me that I ne...
2,2,spotify:track:4AGkBc4BiGLQNBdTUmUeF3,spotify:artist:2sG4zTOLvjKG1PSoOyf5Ej,Touching the Ground,['Brandi Carlile'],False,acoustic pop;folk;indie pop;lilith;modern folk...,Touching the Ground Lyrics I swear when we tou...
3,3,spotify:track:4jtIeveEJPs8SxuVa3FV21,spotify:artist:0c173mlxpT3dSFRgMO8XPh,Nothing Is Stopping You,['Big Sean'],True,detroit hip hop;hip hop;pop;pop rap;rap;southe...,Nothing Is Stopping You Lyrics Nothing is stop...
4,4,spotify:track:5Dbr7Fy5VhSTXRbt2h3EYF,spotify:artist:4TKTii6gnOnUXQHyuo9JaD,I Shall Believe,['Sheryl Crow'],False,lilith;mellow gold;neo mellow;new wave pop;per...,I Shall Believe Lyrics Come to me now And lay ...